Created prefabs and new recolectable items, but couldnt implement on scene1
 on scene1 the same changes make this error to appear, i fought this for hours xd

NullReferenceException: Object reference not set to an instance of an object
InventoryUI.DisplayItem (System.Int32 x, System.Int32 y, System.Single itemSlotCellSize, Item item) (at Assets/Scripts/inventory/InventoryUI.cs:47)
InventoryUI.RefreshInventoryItems () (at Assets/Scripts/inventory/InventoryUI.cs:33)
InventoryUI.AddItem (Item item) (at Assets/Scripts/inventory/InventoryUI.cs:58)
PlayerController.handleItemCollisions (UnityEngine.Collider2D collision) (at Assets/Scripts/PlayerController.cs:62)
PlayerController.OnTriggerEnter2D (UnityEngine.Collider2D collision) (at Assets/Scripts/PlayerController.cs:55)